[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.4.0"
json = "0.12.4"
websocket = "0.26.2"

[dev-dependencies]
dotenv = "0.15.0"
